sudo: false
language: android
before_install:
  - cd android && chmod +x gradlew
android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra
script: gradle assemble --stacktrace
notifications:
  email: false
node_js:
  - '4'
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
